version=23.1
description=Plugin Report Portal For Teams.
pluginId = teams_integration
pluginClass=com.epam.reportportal.extension.template.TemplatePlugin
pluginName = Teams Plugin
provider = astelmakh
license = Apache 2.0
documentation = https://example.com/docomuentation
isIntegrationsAllowed = true
isEmbedded = true
isMultiple = true
mainBinaryData=main.js
yourAdditionalMetadata = yourMetadataValue
yourAdditionalProperty = yourPropertyValue